// -volvo

const dop = [
    {ru:"Установка аксессуаров", eng:"", url:"ustanovka-dop-oborudovaniya/ustanovka-aksessuarov"},
    {ru:"Установка брызговиков", eng:"", url:"ustanovka-dop-oborudovaniya/ustanovka-bryzgovikov"},
    {ru:"Установка видеорегистратора", eng:"", url:"ustanovka-dop-oborudovaniya/ustanovka-videoregistratora"},
    {ru:"Установка защитных сеток", eng:"", url:"ustanovka-dop-oborudovaniya/ustanovka-zashchitnyh-setok"},
    {ru:"Установка защиты ДВС", eng:"", url:"ustanovka-dop-oborudovaniya/ustanovka-zashchity-dvs"},
    {ru:"Установка камеры заднего вида", eng:"", url:"ustanovka-dop-oborudovaniya/ustanovka-kamery-zadnego-vida"},
    {ru:"Установка подкрылка", eng:"", url:"ustanovka-dop-oborudovaniya/ustanovka-podkrylka"},
    {ru:"Установка порогов", eng:"", url:"ustanovka-dop-oborudovaniya/ustanovka-porogov"},
    {ru:"Установка регистратора", eng:"", url:"ustanovka-dop-oborudovaniya/ustanovka-registratora"},
    {ru:"Установка фаркопа", eng:"", url:"ustanovka-dop-oborudovaniya/ustanovka-farkopa"},
    {ru:"Активация Bluetooth audio", eng:"", url:"ustanovka-dop-oborudovaniya/aktivaciya-bluetooth-audio"},
    {ru:"Активация Android Auto", eng:"", url:"ustanovka-dop-oborudovaniya/aktivaciya-android-auto"},
    {ru:"Активация Apple Car Play", eng:"", url:"ustanovka-dop-oborudovaniya/aktivaciya-apple-car-play"},
    {ru:"Отключение мочевины", eng:"", url:"ustanovka-dop-oborudovaniya/otklyuchenie-mocheviny"},
    {ru:"Отключение радарных датчиков", eng:"", url:"ustanovka-dop-oborudovaniya/otklyuchenie-radarnyh-datchikov"},
    {ru:"Отключение системы мертвых зон", eng:"", url:"ustanovka-dop-oborudovaniya/otklyuchenie-sistemy-mertvyh-zon"},
    {ru:"Отключение системы SCR", eng:"", url:"ustanovka-dop-oborudovaniya/otklyuchenie-sistemy-scr"},
    {ru:"Отключение Collision Prevention Assist", eng:"", url:"ustanovka-dop-oborudovaniya/otklyuchenie-collision-prevention-assist"}
];

const diagnostics = [
    {ru:"Диагностика аккумулятора", eng:"", url:"diagnostika/diagnostika-akkumulyatora"},
    {ru:"Диагностика АКПП", eng:"", url:"diagnostika/diagnostika-akpp"},
    {ru:"Диагностика двигателя", eng:"", url:"diagnostika/diagnostika-korobki-dvitagelya"},
    {ru:"Диагностика коробки передач", eng:"", url:"diagnostika/diagnostika-korobki-peredach"},
    {ru:"Диагностика подвески", eng:"", url:"diagnostika/diagnostika-podveski"},
    {ru:"Диагностика течей", eng:"", url:"diagnostika/diagnostika-techey"},
    {ru:"Диагностика шины CAN", eng:"", url:"diagnostika/diagnostika-shiny-can"},
    {ru:"Диагностика электрики", eng:"", url:"diagnostika/diagnostika-ehlektriki"},
    {ru:"Компьютерная диагностика", eng:"", url:"diagnostika/kompyuternaya-diagnostika"},
    {ru:"Комплексная проверка автомобиля", eng:"", url:"diagnostika/kompleksnaya-proverka-avtomobilya"},
    {ru:"Проверка автомобиля перед покупкой", eng:"", url:"diagnostika/proverka-avtomobilya-pered-pokupkoy"},
];

const remont = [
    {ru:"Антибактериальная обработка кондиционера", eng:"", url:"remont/antibakterialnaya-obrabotka-kondicionera"},
{ru:"Загрузка ПО", eng:"", url:"remont/zagruzka-po"},
{ru:"Замена абсорбера", eng:"", url:"remont/zamena-absorbera"},
{ru:"Замена аккумулятора", eng:"", url:"remont/zamena-akkumulyatora"},
{ru:"Замена амортизаторов", eng:"", url:"remont/zamena-amortizatorov"},
{ru:"Замена антифриза", eng:"", url:"remont/zamena-antifriza"},
{ru:"Замена блока двигателя", eng:"", url:"remont/zamena-bloka-dvigatelya"},
{ru:"Замена воздушного фильтра", eng:"", url:"remont/zamena-vozdushnogo-filtra"},
{ru:"Замена генератора", eng:"", url:"remont/zamena-generatora"},
{ru:"Замена головки блока цилиндров", eng:"", url:"remont/zamena-golovki-bloka-cilindrov"},
{ru:"Замена ГРМ D2", eng:"", url:"remont/zamena-grm-d2"},
{ru:"Замена ГРМ D3", eng:"", url:"remont/zamena-grm-d3"},
{ru:"Замена ГРМ D4", eng:"", url:"remont/zamena-grm-d4"},
{ru:"Замена ГРМ D5", eng:"", url:"remont/zamena-grm-d5"},
{ru:"Замена ГРМ T3", eng:"", url:"remont/zamena-grm-t3"},
{ru:"Замена ГРМ T4", eng:"", url:"remont/zamena-grm-t4"},
{ru:"Замена ГРМ T5", eng:"", url:"remont/zamena-grm-t5"},
{ru:"Замена датчика уровня кузова", eng:"", url:"remont/zamena-datchika-urovnya-kuzova"},
{ru:"Замена дисков", eng:"", url:"remont/zamena-diskov"},
{ru:"Замена жидкости ГУР", eng:"", url:"remont/zamena-zhidkosti-gur"},
{ru:"Замена заднего сальника колнвала", eng:"", url:"remont/zamena-zadnego-salnika-kolnvala"},
{ru:"Замена катушки зажигания", eng:"", url:"remont/zamena-katushki-zazhiganiya"},
{ru:"Замена колодок", eng:"", url:"remont/zamena-kolodok"},
{ru:"Замена компрессора кондиционера", eng:"", url:"remont/zamena-kompressora-kondicionera"},
{ru:"Замена компрессора пневмоподвески", eng:"", url:"remont/zamena-kompressora-pnevmopodveski"},
{ru:"Замена корпуса масляного фильтра", eng:"", url:"remont/zamena-korpusa-maslyanogo-filtra"},
{ru:"Замена ламп", eng:"", url:"zamena-lamp"},
{ru:"Замена лобового стекла", eng:"", url:"remont/zamena-lobovogo-stekla"},
{ru:"Замена масла", eng:"", url:"remont/zamena-masla"},
{ru:"Замена масла в АКПП", eng:"", url:"remont/zamena-masla-v-akpp"},
{ru:"Замена масла в двигателе", eng:"", url:"remont/zamena-masla-v-dvigatele"},
{ru:"Замена масла в муфте полного привода", eng:"", url:"remont/zamena-masla-v-mufte-polnogo-privoda"},
{ru:"Замена масла в муфте Халдекс", eng:"", url:"remont/zamena-masla-v-mufte-haldeks"},
{ru:"Замена масла в муфте Haldex", eng:"", url:"remont/zamena-masla-v-mufte-haldex"},
{ru:"Замена маслоохладителя", eng:"", url:"remont/zamena-masloohladitelya"},
{ru:"Замена масляного фильтра", eng:"", url:"remont/zamena-maslyanogo-filtra"},
{ru:"Замена механизма стеклоочистителя", eng:"", url:"remont/zamena-mekhanizma-stekloochistitelya"},
{ru:"Замена моторчика печки", eng:"", url:"remont/zamena-motorchika-pechki"},
{ru:"Замена муфты генератора", eng:"", url:"remont/zamena-mufty-generatora"},
{ru:"Замена насоса ГУР", eng:"", url:"remont/zamena-nasosa-gur"},
{ru:"Замена насоса муфты полного привода", eng:"", url:"remont/zamena-nasosa-mufty-polnogo-privoda"},
{ru:"Замена насоса муфты Халдекс", eng:"", url:"remont/zamena-nasosa-mufty-haldeks"},
{ru:"Замена насоса муфты Haldex", eng:"", url:"remont/zamena-nasosa-mufty-haldex"},
{ru:"Замена насоса охлаждающей жидкости", eng:"", url:"remont/zamena-nasosa-ohlazhdayushchey-zhidkosti"},
{ru:"Замена насоса Халдекс", eng:"", url:"remont/zamena-nasosa-haldeks"},
{ru:"Замена насоса Haldex", eng:"", url:"remont/zamena-nasosa-haldex"},
{ru:"Замена опроных подшипников", eng:"", url:"remont/zamena-opronyh-podshipnikov"},
{ru:"Замена охлаждающей жидкости", eng:"", url:"remont/zamena-ohlazhdayushchey-zhidkosti"},
{ru:"Замена охлаждющей жидкости", eng:"", url:"remont/zamena-ohlazhdyushchey-zhidkosti"},
{ru:"Замена патрубков наддува воздуха", eng:"", url:"remont/zamena-patrubkov-nadduva-vozduha"},
{ru:"Замена патрубков охлаждающей жидкости", eng:"", url:"remont/zamena-patrubkov-ohlazhdayushchey-zhidkosti"},
{ru:"Замена переднего сальника колнвала", eng:"", url:"remont/zamena-perednego-salnika-kolnvala"},
{ru:"Замена пневмобаллона", eng:"", url:"remont/zamena-pnevmoballona"},
{ru:"Замена пневмостойки", eng:"", url:"remont/zamena-pnevmostoyki"},
{ru:"Замена подушек двигателя", eng:"", url:"remont/zamena-podushek-dvigatelya"},
{ru:"Замена полуоси", eng:"", url:"remont/zamena-poluosi"},
{ru:"Замена помпы", eng:"", url:"remont/zamena-pompy"},
{ru:"Замена предохранителя", eng:"", url:"remont/zamena-predohranitelya"},
{ru:"Замена привода", eng:"", url:"remont/zamena-privoda"},
{ru:"Замена прокладки", eng:"", url:"remont/zamena-prokladki"},
{ru:"Замена прокладки впускного коллектора", eng:"", url:"remont/zamena-prokladki-vpusknogo-kollektora"},
{ru:"Замена прокладки выпускного коллектора", eng:"", url:"remont/zamena-prokladki-vypusknogo-kollektora"},
{ru:"Замена пружин", eng:"", url:"remont/zamena-pruzhin"},
{ru:"Замена радиатора", eng:"", url:"remont/zamena-radiatora"},
{ru:"Замена ремня вспомогательного оборудования", eng:"", url:"remont/zamena-remnya-vspomogatelnogo-oborudovaniya"},
{ru:"Замена ремня генератора", eng:"", url:"remont/zamena-remnya-generatora"},
{ru:"Замена ремня гидроусилителя", eng:"", url:"remont/zamena-remnya-gidrousilitelya"},
{ru:"Замена ремня кондиционера", eng:"", url:"remont/zamena-remnya-kondicionera"},
{ru:"Замена ремня навесного оборудования", eng:"", url:"remont/zamena-remnya-navesnogo-oborudovaniya"},
{ru:"Замена рулевой рейки", eng:"", url:"remont/zamena-rulevoy-reyki"},
{ru:"Замена рулевых наконечников", eng:"", url:"remont/zamena-rulevyh-nakonechnikov"},
{ru:"Замена рулевых тяг", eng:"", url:"remont/zamena-rulevyh-tyag"},
{ru:"Замена рычагов задних поперечных", eng:"", url:"remont/zamena-rychagov-zadnih-poperechnyh"},
{ru:"Замена рычагов задних продольных", eng:"", url:"remont/zamena-rychagov-zadnih-prodolnyh"},
{ru:"Замена рычагов передних", eng:"", url:"remont/zamena-rychagov-perednih"},
{ru:"Замена рычагов передних поперечных", eng:"", url:"remont/zamena-rychagov-perednih-poperechnyh"},
{ru:"Замена рычагов передних продольных", eng:"", url:"remont/zamena-rychagov-perednih-prodolnyh"},
{ru:"Замена сайлентблоков", eng:"", url:"remont/zamena-saylentblokov"},
{ru:"Замена сайлентблоков задних рычагов", eng:"", url:"remont/zamena-saylentblokov-zadnih-rychagov"},
{ru:"Замена сайлентблоков передних рычагов", eng:"", url:"remont/zamena-saylentblokov-perednih-rychagov"},
{ru:"Замена салников АКПП", eng:"", url:"remont/zamena-salnikov-akpp"},
{ru:"Замена салонного фильтра", eng:"", url:"remont/zamena-salonnogo-filtra"},
{ru:"Замена сальника колнвала", eng:"", url:"remont/zamena-salnika-kolnvala"},
{ru:"Замена сальников", eng:"", url:"remont/zamena-salnikov"},
{ru:"Замена сальников раздаточной коробки", eng:"", url:"remont/zamena-salnikov-razdatochnoy-korobki"},
{ru:"Замена свечей зажигания", eng:"", url:"remont/zamena-svechey-zazhiganiya"},
{ru:"Замена свечи накаливания", eng:"", url:"remont/zamena-svechi-nakalivaniya"},
{ru:"Замена стабилизатора", eng:"", url:"remont/zamena-stabilizatora"},
{ru:"Замена стартера", eng:"", url:"remont/zamena-startera"},
{ru:"Замена стекла", eng:"", url:"remont/zamena-stekla"},
{ru:"Замена стоек стабилизатора", eng:"", url:"remont/zamena-stoek-stabilizatora"},
{ru:"Замена стоек стабилизатора задних", eng:"", url:"remont/zamena-stoek-stabilizatora-zadnih"},
{ru:"Замена стоек стабилизатора передних", eng:"", url:"remont/zamena-stoek-stabilizatora-perednih"},
{ru:"Замена стойки стабилизатора", eng:"", url:"remont/zamena-stoyki-stabilizatora"},
{ru:"Замена супортов", eng:"", url:"remont/zamena-suportov"},
{ru:"Замена ТНВД", eng:"", url:"remont/zamena-tnvd"},
{ru:"Замена топливного насоса", eng:"", url:"remont/zamena-toplivnogo-nasosa"},
{ru:"Замена топливного фильтра", eng:"", url:"remont/zamena-toplivnogo-filtra"},
{ru:"Замена топливного шланга", eng:"", url:"remont/zamena-toplivnogo-shlanga"},
{ru:"Замена топливной трубки", eng:"", url:"remont/zamena-toplivnoy-trubki"},
{ru:"Замена топливных форсунок", eng:"", url:"remont/zamena-toplivnyh-forsunok"},
{ru:"Замена тормозного шланга", eng:"", url:"remont/zamena-tormoznogo-shlanga"},
{ru:"Замена тормозной жидкости", eng:"", url:"remont/zamena-tormoznoy-zhidkosti"},
{ru:"Замена тормозной трубки", eng:"", url:"remont/zamena-tormoznoy-trubki"},
{ru:"Замена тормозных дисков", eng:"", url:"remont/zamena-tormoznyh-diskov"},
{ru:"Замена тормозных колодок", eng:"", url:"remont/zamena-tormoznyh-kolodok"},
{ru:"Замена трапеции стеклоочистителя", eng:"", url:"remont/zamena-trapecii-stekloochistitelya"},
{ru:"Замена турбины", eng:"", url:"remont/zamena-turbiny"},
{ru:"Замена тяги вихревых заслонок", eng:"", url:"remont/zamena-tyagi-vihrevyh-zaslonok"},
{ru:"Замена форсунок", eng:"", url:"remont/zamena-forsunok"},
{ru:"Замена Шруса", eng:"", url:"remont/zamena-shrusa"},
{ru:"Замена щеток стеклоочистителя", eng:"", url:"remont/zamena-shchetok-stekloochistitelya"},
{ru:"Заправка кондиционеров", eng:"", url:"remont/zapravka-kondicionerov"},
{ru:"Зарядка аккумулятора", eng:"", url:"remont/zaryadka-akkumulyatora"},
{ru:"Мойка радиаторов", eng:"", url:"remont/moyka-radiatorov"},
{ru:"Обновление ПО", eng:"", url:"remont/obnovlenie-po"},
{ru:"Переуплотнение двигателя", eng:"", url:"remont/pereuplotnenie-dvigatelya"},
{ru:"Прожиг сажевого фильтра", eng:"", url:"remont/prozhig-sazhevogo-filtra"},
{ru:"Промывка топливных форсунок", eng:"", url:"remont/promyvka-toplivnyh-forsunok"},
{ru:"Промывка форсунок", eng:"", url:"remont/promyvka-forsunok"},
{ru:"Регенерация сажевого фильтра", eng:"", url:"remont/regeneraciya-sazhevogo-filtra"},
{ru:"Регулировка фар", eng:"", url:"remont/regulirovka-far"},
{ru:"Ремонт автоматической коробки передач", eng:"", url:"remont/remont-avtomaticheskoy-korobki-peredach"},
{ru:"Ремонт АКПП", eng:"", url:"remont/remont-akpp"},
{ru:"Ремонт генератора", eng:"", url:"remont/remont-generatora"},
{ru:"Ремонт двигателя", eng:"", url:"remont/remont-dvigatelya"},
{ru:"Ремонт замков дверей", eng:"", url:"remont/remont-zamkov-dverey"},
{ru:"Ремонт кондиционеров", eng:"", url:"remont/remont-kondicionerov"},
{ru:"Ремонт лобового стекла", eng:"", url:"remont/remont-lobovogo-stekla"},
{ru:"Ремонт подвески", eng:"", url:"remont/remont-podveski"},
{ru:"Ремонт прикуривателя", eng:"", url:"remont/remont-prikurivatelya"},
{ru:"Ремонт проводки", eng:"", url:"remont/remont-provodki"},
{ru:"Ремонт розетки 12V", eng:"", url:"remont/remont-rozetki-12v"},
{ru:"Ремонт рулевой рейки", eng:"", url:"remont/remont-rulevoy-reyki"},
{ru:"Ремонт салонной розетки", eng:"", url:"remont/remont-salonnoy-rozetki"},
{ru:"Ремонт стартера", eng:"", url:"remont/remont-startera"},
{ru:"Ремонт суппортов", eng:"", url:"remont/remont-supportov"},
{ru:"Ремонт турбины", eng:"", url:"remont/remont-turbiny"},
{ru:"Ремонт электропроводки", eng:"", url:"remont/remont-ehlektroprovodki"},
{ru:"Смазка люка", eng:"", url:"remont/smazka-lyuka"},
{ru:"Чистка дроссельной заслонки", eng:"", url:"remont/chistka-drosselnoy-zaslonki"},
{ru:"Чистка клапана ЕГР", eng:"", url:"remont/chistka-klapana-egr"},
{ru:"Чистка клапана EGR", eng:"", url:"remont/chistka-klapana-egr"}
];
export {
    dop,
    diagnostics,
    remont
}